[tool.pyright]
include = ["src", "tests"]
exclude = ["**/node_modules",
    "**/__pycache__",
]
venv = "venv"
# typing
typeCheckingMode = "strict"
reportMissingTypeArgument = false
reportUnknownVariableType = false
# python
pythonVersion = "3.11"
pythonPlatform = "Linux"

